services:
  dev:
    container_name: node-lua-state
    command: sleep infinity
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      HISTFILE: /home/node/lua-state/tmp/.bash-history
      PROMPT_COMMAND: "history -a"
    volumes:
      - .:/home/node/lua-state:cache
