name: Publish Package

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write

jobs:
  release_native:
    name: Release Native Binaries
    uses: ./.github/workflows/release-native.yml

  publish_package:
    name: Publish Package
    runs-on: ubuntu-22.04
    needs: release_native
    steps:
      - uses: actions/checkout@v4
      - name: Install Nodejs
        uses: actions/setup-node@v6
        with:
          node-version: 24.10.0
          registry-url: https://registry.npmjs.org
      - name: Publish Package
        run: npm publish